### ISSUE TITLE
Porting to Python 3.3 or higher and Django 1.6 or higher

### ISSUE THREAD

**Issue by luzfcb** [bread-and-pepper/django-userena#398]
Hello, I think now it's time to begin efforts for porting this excellent library for Python 3 and Django 1.6 or higher.
On a personal opinion, I believe it should be supported python3.3 or higher, mainly because Python 3.4 was released today, and adds many new features useful. The longer we delay when porting to Python3, the more painful it will be, and consequently all the effort of everyone with this library will be lost. 
I started a few modifications to it, and I've had some progress, at least make the tests run.

see compare of my python-33 branch: https://github.com/luzfcb/django-userena/compare/python-33

One of the changes I made, to facilitate testing, was not using the tox tests in travis.org.
See my changes on .travis.yml file: https://github.com/luzfcb/django-userena/blob/python-33/.travis.yml

See my latest build on travis: https://travis-ci.org/luzfcb/django-userena/builds/20909895

These parts result in errors in Python3
https://github.com/luzfcb/django-userena/blob/python-33/userena/utils.py#L70
https://github.com/luzfcb/django-userena/blob/python-33/userena/utils.py#L126-L127
https://github.com/luzfcb/django-userena/blob/python-33/userena/forms.py#L116

Django 1.7:
In django 1.7 how the apps are loaded was modified. Now it is necessary to create a class that inherits from AppConfig, and some other modifications. 
I have not had time to look into this deeper
https://docs.djangoproject.com/en/dev/ref/applications/

Sorry for ugly English. I'm still learning ... I speak Brazilian Portuguese.

Some useful documentations:
http://alexgaynor.net/2013/dec/30/about-python-3/
http://getpython3.com/
https://docs.djangoproject.com/en/dev/topics/python3/
http://developerblog.redhat.com/2014/02/18/migrate-to-python3-w-rhscl/
https://ncoghlan_devs-python-notes.readthedocs.org/en/latest/python3/binary_protocols.html

**Comment by swistakm** [comment]
This already is fixed for a very long time.
