### ISSUE TITLE
Query about Userena Status and beyond Django 1.8

### ISSUE THREAD

**Issue by hrishiballal** [bread-and-pepper/django-userena#450]
Hi All, 
I was just wondering about the status of this project particularly when Django 1.8 is released, would it be compatible with that release? There is some confusion about the work that is required to make it compatible.

**Comment by swistakm** [comment]
If anyone will have time to test/implement then it will be compatibile :). 

I would like to have it earlier than last time with django1.7. I think that best time to start working on it will be around beta of django1.8 (end of February).
