### ISSUE TITLE
django userena could support python3.2   

### ISSUE THREAD

**Issue by iloveyo123u1** [bread-and-pepper/django-userena#453]
how are you 
thanks

https://github.com/bread-and-pepper/django-userena/blob/master/userena/forms.py#L124
https://github.com/bread-and-pepper/django-userena/blob/master/userena/forms.py#L148
https://github.com/bread-and-pepper/django-userena/blob/master/userena/forms.py#L149
https://github.com/bread-and-pepper/django-userena/blob/master/userena/forms.py#L154

u''      this is python2

**Comment by swistakm** [comment]
this can be fixed using six
