### ISSUE TITLE
create_user on UserenaSignup model failed on python 3.4

### ISSUE THREAD

**Issue by pyghassen** [bread-and-pepper/django-userena#455]
I was trying to create a user using the UserenaSignup model, but I faced this problem.

```
    user = UserenaSignup.objects.create_user("test", "test@t.com", "test", active=True, send_email=False)
    print(user)
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-13-b7da53fda433> in <module>()
    ----> 1 print(u)

    TypeError: __str__ returned non-string (type bytes)
```

**Comment by swistakm** [comment]
Coukld you provide django-userena version?

**Comment by pyghassen** [comment]
Yes in deed, to be honest I did not try any other version of python.

**Comment by swistakm** [comment]
Sorry. I was wrong. I succeeded to replicate that issue.

**Comment by swistakm** [comment]
Ok. I have added test. It was failing with 1.4.0 version but it seems that is already fixed by other changes in current master branch.
