### ISSUE TITLE
create_user_profile alters username

### ISSUE THREAD

**Issue by st8st8** [bread-and-pepper/django-userena#456]
In managers.py, create_user_profile this happens (python 2)

        if isinstance(user.username, text_type):
            user.username = user.username.encode('utf-8')

Which means my unicode username gets returned as a garbled ascii str when I save my user which a non-ascii username.

**Comment by st8st8** [comment]
This in turn breaks the sha1 generator as it received a string twice encoded to utf8.  I've commented out these lines in my fork of this...

**Comment by alex-alvarez** [comment]
I think I'm facing the same bug. In my site, users who sign up with non-ascii usernames get a server error 500 and the activation email is not send, so they cannot activate their account.

**Comment by leonardoo** [comment]
hi, I made this little test in django 1.4 shel

```python
u'hóla' == u"hóla".encode("utf-8") #False
from userena.compat import smart_text
u'hóla' == smart_text(u"hóla") # True
```
python2 is a little annoying with the utf-8
