### ISSUE TITLE
how do I uninstall userena

### ISSUE THREAD

**Issue by percy3d** [bread-and-pepper/django-userena#471]
I've moved onto a different authentication system and want to know how I remove userena completely. I am able to remove all references from within settings but I get errors when trying to delete an existing user....

update or delete on table "auth_user" violates foreign key constraint "guardian_userobjectpermission_user_id_fkey" on table "guardian_userobjectpermission"
DETAIL:  Key (id)=(157) is still referenced from table "guardian_userobjectpermission".

How do I go about removing userena altogether while keeping my users. Do I need to drop tables userprofile and guardian_userobjectpermission?

**Comment by swistakm** [comment]
yes, you should drop tables that are not required anymore. Have you tried django `sqlclear` command?

**Comment by swistakm** [comment]
I assume you solved your problem.

**Comment by percy3d** [comment]
Sure did.

<dan />
