### ISSUE TITLE
Mugshot quality?

### ISSUE THREAD

**Issue by deronsizemore** [bread-and-pepper/django-userena#478]
I'm wondering if there's a setting somewhere or a snippet of code I can alter which will allow me to up the quality that mugshot images save?

As long as the image I'm uploading is a .jpg, it seems to function fine, but if the image is a .png or .gif, there's a noticeable degradation in quality.

Here's an example of an image that was originally a .png (which after uploaded and re-saved as a mugshot was renamed a .jpg): https://golfledger-dev.s3.amazonaws.com/uploads/mugshots/987fc8fc3b.jpg

you can see above around the white arrows, there's some darker areas which aren't quite crisp.

contrast that with this image: https://golfledger.s3.amazonaws.com/uploads/mugshots/47bbb43c3a.jpg

which was originally a .jpg, and it's crisp as can be.

What can I do to ensure quality is high?

**Comment by deronsizemore** [comment]
I figured this out for those curious. Userena uses easy_thumbnails to resize and crop images. Upping the quality of profile images is as simple as placing this in your settings.py:

THUMBNAIL_QUALITY = 95

I didn't go to 100 simply because easy_thumbnails recommended not to.

**Comment by swistakm** [comment]
Sorry for no response. I'm glad you found solution. I will add this to FAQ for future reference.

**Comment by deronsizemore** [comment]
No worries! Thanks!
