### ISSUE TITLE
User created outside of Userena workflow cannot edit profile

### ISSUE THREAD

**Issue by deronsizemore** [bread-and-pepper/django-userena#481]
Hi,

I've got a site where Userena is working great. I'm trying to build the community and am taking the Reddit approach, i.e., creating user accounts on the fly as I submit new posts. I have an input field which accepts a string and upon submitting the post, if that user doesn't exist, then I create the user and then create the profile for that user. All of that seems to work fine. The new post submits as that new user, I'm able to visit that users profile on the front-end, I'm able to log in as them, etc. However, when I log in as that user and attempt to edit their profile all I get is a blank white page. I don't have this issue for any other user who's been created using the normal Userena workflow, i.e., signup form, click activation link in email, etc.

Can anyone tell me what might be going wrong here? Here's my code that's doing the work to create a new user when a new post is submitted (sorry, still learning, this may be a mess...)

    if request.POST.get('username'):
        new_user = User(username=request.POST.get('username'), email='', password=make_password('password', salt=None, hasher='default'))
	new_user.save()
	post.submitter = new_user
        profile_model = get_profile_model()
        profile = profile_model.objects.create(user=new_user)

**Comment by swistakm** [comment]
You should use `UserenaSignup.objects.create_user()` method instead. In your case it will be something like:

    new_user = YourProfileModel.objects.create_user(
        username=request.POST.get('username'),
        email='', 
        password=make_password('password', salt=None, hasher='default'),
        active=True,
        send_email=False,
    )
    

Note that `active` keyword controls if user requires clicking activation link in email and `send_email` tells if activation email should be sent. This method will additionally create proper profile instance. For more details see code of this method:
https://github.com/bread-and-pepper/django-userena/blob/939dea81592ce1e45b65a377e95de5dbba7a9352/userena/managers.py#L37

**Comment by deronsizemore** [comment]
Thanks for the quick reply.

Bear with me and my ignorance, but it's not immediately obvious to me what I should use in place of "YourProfileModel?"

My profile model is "MyProfile" so I assumed I'd use that and thus have:

			if request.POST.get('username'):
				new_user = MyProfile.objects.create_user(
				    username=request.POST.get('username'),
				    email='', 
				    password=make_password('password', salt=None, hasher='default'),
				    active=True,
				    send_email=False,
				)

I get this error:

'UserenaBaseProfileManager' object has no attribute 'create_user'

**Comment by swistakm** [comment]
Sorry, for my mistake. It should be `UserenaSignup.objects.create_user(...)`. I haven't used userena for a while...

**Comment by deronsizemore** [comment]
Ok, no problem. That seems to work as far as creating the user. Thanks.

When I try to log in as that newly created user, it won't allow me to log in. Just tells me username or password is incorrect. Any ideas on that? It's like the account isn't active or something. When I view that profile, for the "activation key" field it has: fa62e191b045c243f7dbfe84b14844b83901cc45 where the other users who are active and signed up the regular way say: ALREADY_ACTIVATED. Does that have something to do with it?

My code:

    new_user = UserenaSignup.objects.create_user(
				    username=request.POST.get('username'),
				    email='', 
				    password=make_password('Michaelq2w3e4!', salt=None, hasher='default'),
				    active=True,
				    send_email=False,
				)

**Comment by deronsizemore** [comment]
Sorry, I see now that active=True isn't what I thought it was. Needs to be False if I want them to not have email activation. Sorry I overlooked that from your previous comment earlier.

**Comment by deronsizemore** [comment]
Ok... active=True is in fact what I thought it was. lol. It sets the user to active or not. But it appears that my problem is that even though the the "active" boolean is checked, that it thinks the user isn't actually active because it's still showing that unique key in the "activation key" field in the admin area of the profile

**Comment by deronsizemore** [comment]
Okay, so, I'm close. :)

Turns out that if I create a user with the code from above, it works great. The problem is I can't log into the site with that user's credentials. However, if I go into the admin area and change that users password manually, I can then log in. So, the UserenaSignup.objects.create_user() doesn't seem to acknowledge the password I'm setting in the arguments. I'd love to hear any ideas on this as I continue to search for the answer.

Thanks.

**Comment by swistakm** [comment]
I think the reason is very simple. You can not authenticate using those credentials because they are wrong. 

And now in details. How do you set password? Probably like `create_user(..., password=make_password('password', salt=None, hasher='default')`. If yes, then this is wrong. Usually the best approach in django is to use `User.objects.create_user` method to create users so you do need to play with some lower level things like hashing the password. Userena takes the same approach: you pass plain password to the method and it already knows what to do (this is by the way one of the reasons why `django.contrib.auth` exists). In fact this will call mentioned `User.objects.create_user` method with the same parameters.

I sorry for giving you some code samples that might be misleading but I was focused on other issue so simply copied other params and assumed that you will know what to do with the rest.

**Comment by deronsizemore** [comment]
Thanks! So, unless I'm missing something, it appears that all I needed to change was this line:

    password=make_password('password', salt=None, hasher='default'),

from the Userena.objects.create_user() method.

Once changed to:

    password='password'

It seems to work. So I guess it was trying to do some double encryption or something?

Everything looks correct and it now allows me to log in. I just want to make sure I'm not misunderstanding you since you recommended above that I use something like User.object.create_user()?

Thanks. Sorry for confusion.

**Comment by swistakm** [comment]
> It seems to work. So I guess it was trying to do some double encryption or something?

Yes

> Everything looks correct and it now allows me to log in. I just want to make sure I'm not misunderstanding you since you recommended above that I use something like User.object.create_user()?

Now everything should be fine. I have mentioned this method on User model manager to give you a general advice. Obviously if you are using userena then `UserenaSignup.objects.create_user` method will call this for you.

**Comment by deronsizemore** [comment]
Ok, great. Thanks for your help
