### ISSUE TITLE
Removed django warning: RemovedInDjango19Warning

### ISSUE THREAD

**Issue by nooperpudd** [bread-and-pepper/django-userena#488]
`site-packages/userena/utils.py:133: RemovedInDjango19Warning: django.db.models.get_model is deprecated.
  profile_mod = get_model(*settings.AUTH_PROFILE_MODULE.rsplit('.', 1))`

**Comment by leonardoo** [comment]
@nooperpudd this issue is fix #485, but you must wait to the new release

**Comment by swistakm** [comment]
Fixed and released as part of #505
