### ISSUE TITLE
Limiting Users Profile List?

### ISSUE THREAD

**Issue by alzearafat** [bread-and-pepper/django-userena#503]
Hi,

How I can limiting users profile list? I want to show only 10 profiles, instead of 50. How I can make this possible without editing the core plugin/userena?

Please excuse my English :)
Thanks in advance,
Regards

**Comment by swistakm** [comment]
simply rewrite urlconf rule for `'userena_profile_list_paginated'`  and `''userena_profile_list'`views located [here](https://github.com/bread-and-pepper/django-userena/blob/master/userena/urls.py#L108) using `paginate_by` param like:

```
url(
    r'^page/(?P<page>[0-9]+)/$',
    userena_views.ProfileListView.as_view(paginate_by=10),
    name='userena_profile_list_paginated'
)
```

This approach applies for customising other views behaviour. Those params are probably not documented yet so please refer to userena code if you are in doubt.

If this solved your problem then please close the issue.

**Comment by swistakm** [comment]
Also some off-topic personal advices for you:
* Do not use excessive question marks in message titles. This is considered rude.
* Do not thank in advance. This is **sometimes** considered rude.
* Do not excuse for your english unless someone forces you by making fun of you. Instead try your best to make it correct. This is simply pointless.

**Comment by alzearafat** [comment]
Hi @swistakm 

Thank you, it's really helps :D 
Also thank you for your advice, I really appreciate it ;)

Regards,
