### ISSUE TITLE
How integrate social-auth? (Add to documentation)

### ISSUE THREAD

**Issue by bittner** [bread-and-pepper/django-userena#514]
What is the appropriate way to integrate social authentication (e.g. [python-social-auth](https://github.com/omab/python-social-auth) or [django-allauth](https://github.com/pennersr/django-allauth))?

[Information around about this](http://stackoverflow.com/questions/12467383/how-to-accomplish-integration-of-django-userena-and-social-auth#12502542) is quite dated, and sometimes refers to `allauth` as an *alternative* (which it isn't, especially if you want user messaging).

* Can we add a recommended approach to the documentation?
* Can we add some code to make the integration easier? (plug-and-play experience)

**Comment by swistakm** [comment]
> What is the appropriate way to integrate social authentication (e.g. python-social-auth or django-allauth)?

Someone familiar with these projects needs to say something. Unfortunately I'm not so I don't know. This needs someone's research.

> * Can we add a recommended approach to the documentation?

Yes and contributions are welcome.

> * Can we add some code to make the integration easier? (plug-and-play experience)

Yes and contributions are welcome.

**Comment by swistakm** [comment]
I close because there is no interest and no one willing to do it.
