### ISSUE TITLE
Is Userena still alive?

### ISSUE THREAD

**Issue by ecoluzmx** [bread-and-pepper/django-userena#549]
The last commit is from a year ago. Is it safe to use Userena in a project or is it having issues with the last django release?

**Comment by swistakm** [comment]
The project is dead.

Michał Jaworski

Dnia 03.08.2017 o godz. 03:27 ecoluzmx <notifications@github.com> napisał(a):

**Comment by apachano** [comment]
If the project is dead what is a suggested alternative?

**Comment by ecoluzmx** [comment]
@swistakm This is bad news, userena was a very good solution. 
 @apachano I'm gonna try with django-user-accounts
